version: '3'
services:
  webapi:
    image: tickend-api
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    volumes:
      - c:/temp/Tickend/WebApi/appsettings.json:/app/appsettings.json
      - c:/temp/Tickend/WebApi/Logs:/app/Temp/Logs
    networks:
      - networktickend
  webapp:
    image: tickend-web
    ports:
      - "8082:8082"
    restart: unless-stopped
    volumes:
      - c:/temp/Tickend/WebApp/.env:/app/.env
      - c:/temp/Tickend/WebApp/ssl:/app/ssl
    networks:
      - networktickend
  database:
    image: tickend-db
    ports:
      - "1439:1433"
    environment:
    - SA_PASSWORD=Test!2039
    restart: unless-stopped
    volumes:
      - c:/temp/Tickend/Database/data:/var/opt/mssql/data
      - c:/temp/Tickend/Database/log:/var/opt/mssql/log 
      - c:/temp/Tickend/Database/secrets:/var/opt/mssql/secrets
    networks:
      - networktickend
networks:
  networktickend:
