export interface TicketResponse {
    id: number,
    title: string,
    description: string,
    projectId: number,
    ticketTypeId: number,
    ticketPriorityId: number,
    ticketStatusId: number,
    dateCreated: Date | string,
    dateUpdated: Date | string,
    dateClosed: Date | string,
    createBy: number,
    lastUpdatedBy: number,
    closedBy: number,
    isClosed: boolean,
    ip: string,
    os: string,
    browser: string,
    reply: number,
}