CREATE TABLE [dbo].[AuditLog]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] INT FOREIGN KEY REFERENCES [User](Id),
	[Action] TINYINT NOT NULL,
	[Date] DATETIME NOT NULL,
	[Table] VARCHAR(MAX) NOT NULL,
	[PrimaryId] VARCHAR(MAX) NOT NULL,
	[OrganizationId] INT FOREIGN KEY REFERENCES [Organization](Id) NULL,
)
