CREATE TABLE [dbo].[AuditLogDetails]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[AudidLogId] BIGINT NOT NULL FOREIGN KEY REFERENCES AuditLog(Id),
	[ColumnName] VARCHAR(MAX) NOT NULL,
	[OldValue] VARCHAR(MAX) NULL,
	[NewValue] VARCHAR(MAX) NOT NULL,
	[TypeValue] TINYINT NOT NULL
)
