CREATE TABLE [dbo].[ProjectXDeveloper]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ProjectId] INT NOT NULL FOREIGN KEY REFERENCES [Project](Id),
	[DeveloperId] INT NOT NULL FOREIGN KEY REFERENCES [User](Id)
)
