import { useEffect } from "react";

export const paths = {
  home: "/",
  users: "/Users",
  newUser: "/Users/New",
  editUser: "/Users/Edit/",
  editUserWithId: "/Users/Edit/:id",
  roles: "/Roles",
  newRol: "/Roles/New",
  editRol: "/Roles/Edit/",
  editRolWithId: "/Roles/Edit/:id",
  menus: "/Menus",
  newMenus: "/Menus/New",
  editMenus: "/Menus/Edit/",
  editMenusWithId: "/Menus/Edit/:id",
  ticketTypes: "/Ticket/Types",
  newTicketType: "/Ticket/Types/New",
  EditTicketType: "/Ticket/Types/Edit",
  EditTicketTypeWithId: "/Ticket/Types/Edit/:id",
  ticketStatus: "/Ticket/Status",
  newTicketStatus: "/Ticket/Status/New",
  EditTicketStatus: "/Ticket/Status/Edit",
  EditTicketStatusWithId: "/Ticket/Status/Edit/:id",
  ticketPriorities: "/Ticket/Priorities",
  newTicketPriorities: "/Ticket/Priorities/New",
  EditTicketPriorities: "/Ticket/Priorities/Edit",
  EditTicketPrioritiesWithId: "/Ticket/Priorities/Edit/:id",
};
