name: publish

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
        
jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
              
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.TOKEN_DEPLOY }}
                
            - name: Build image
              run:  |
                docker build . --tag ghcr.io/kfernandol/tickend:latest
                docker push ghcr.io/kfernandol/tickend:latest
    
    deploy:
        needs: create-docker-image
        runs-on: ubuntu-latest
        steps:
            - name: Install sshpass
              run: sudo apt-get install -y sshpass
                
            - name: Install Docker
              run: |
                sudo apt-get update
                sudo apt-get install -y ca-certificates curl gnupg lsb-release
                mkdir -p /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                sudo apt-get update
                sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            
            - name: SSH into Server
              run: |
                   sshpass -p ${{secrets.AUTH_PASS}} ssh -o StrictHostKeyChecking=no ${{secrets.AUTH_SERVER}} << EOF
                    cd /home/Projects/NET/Tickend/
                    docker login ghcr.io -u kfernandol -p ${{secrets.TOKEN_DEPLOY}}
                    docker pull ghcr.io/kfernandol/tickend:latest
                    docker stop tickend && docker rm tickend
                    docker-compose down
                    docker-compose up -d