name: publish

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
        
jobs:
    create-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
              
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.TOKEN_DEPLOY }}
                
            - name: Build WEBAPI IMAGE
              run:  |
                docker build ./WebApi --tag ghcr.io/kfernandol/tickend-webapi:latest
                docker push ghcr.io/kfernandol/tickend-webapi:latest
    
            - name: Build WEBAPP image
              run:  |
                docker build ./WebApp --tag ghcr.io/kfernandol/tickend-webapp:latest
                docker push ghcr.io/kfernandol/tickend-webapp:latest
                
            - name: Build Database image
              run:  |
                docker build ./Database --tag ghcr.io/kfernandol/tickend-database:latest
                docker push ghcr.io/kfernandol/tickend-database:latest
    deploy:
        needs: create-docker-image
        runs-on: ubuntu-latest
        steps:
            - name: Install sshpass
              run: sudo apt-get install -y sshpass
            
            - name: SSH into Server
              run: |
                   sshpass -p ${{secrets.AUTH_PASS}} ssh -o StrictHostKeyChecking=no ${{secrets.AUTH_SERVER}} << EOF
                    cd /home/Docker/Tickend/
                    docker login ghcr.io -u kfernandol -p ${{secrets.TOKEN_DEPLOY}}
                    docker pull ghcr.io/kfernandol/tickend-webapi:latest
                    docker pull ghcr.io/kfernandol/tickend-webapp:latest
                    docker pull ghcr.io/kfernandol/tickend-database:latest
                    docker stop tickend && docker rm tickend
                    docker-compose down
                    docker-compose up -d